version: 2.1

orbs:
  node: circleci/node@6.1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.11.1

    working_directory: ~/test-api

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # Run linting
      - run:
          name: Run ESLint
          command: npm run lint

      # Run tests with coverage
      - run:
          name: Run tests
          command: npm run test:cov

      # Store test results
      - store_test_results:
          path: coverage

      # Store coverage artifacts
      - store_artifacts:
          path: coverage
          destination: coverage

      # Build the application
      - run:
          name: Build application
          command: npm run build

      # Store build artifacts
      - store_artifacts:
          path: dist
          destination: dist

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
